### ISSUE TITLE
Hope to add a SWITCHING APP feature

### ISSUE THREAD

**Issue by Loyalsoldier** [appetizermonster/hain#100]
Maybe the most important thing on Windows is to switch apps as quickly as we can, especially when our screens are small with so many apps opening. Hope to add that!

**Comment by appetizermonster** [comment]
I suppose this can be implemented with plugin!

**Comment by AlexVanderbist** [comment]
So far I've only found [this plugin](https://www.npmjs.com/package/hain-plugin-cmdow). It seems to do the job but it's nothing like Spotlight on a Mac...
