### ISSUE TITLE
Open hain by plugin

### ISSUE THREAD

**Issue by KennethWussmann** [appetizermonster/hain#101]
Hey, 

it would be nice to have something like `pluginContext.app.show()` to open the Hain-Window again.

Little use-case: I develop a twitter plugin right now and need to generate oAuth-Tokens with my webserver and it would be nice to open Hain after generating them. 

thanks,
~ Kenneth

**Comment by appetizermonster** [comment]
I think this is a good feature for plugins

**Comment by appetizermonster** [comment]
and i think `app.show('some input');` can be useful.

**Comment by mistic100** [comment]
I use the new `open` method to "keep" Hain opened after opening an URL from the RSS feed.
But for some reason I have to add a timeout of 100ms, otherwise the window does not re-open

https://github.com/mistic100/hain-plugin-rss/blob/0f60e0ffc59dc35270eba67b4fb39c2a0bc3027b/index.js#L221-L227

**Comment by appetizermonster** [comment]
@mistic100 `shell.openExternal` doesn't close hain, Losing focus makes hain close itself.
I don't understand a benefit for keeping hain from closing. could you explain it?

**Comment by mistic100** [comment]
Typically when browsing the RSS feed, it's handy to open multiple items in the browser and then read them all. Instead of open one, reopen Hain, navigate to the feed, open another, etc.

**Comment by appetizermonster** [comment]
Okay, I got it. I will try to implement it.

**Comment by appetizermonster** [comment]
Resolved at v0.3.0 (See https://github.com/appetizermonster/hain/blob/v0.3.0/docs/plugin-context-app.md)
