### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by ramstein74** [appetizermonster/hain#104]
npm run dev gives this error... can u help?
![image](https://cloud.githubusercontent.com/assets/1210858/14312580/c82f0fe0-fbe4-11e5-92a8-cf8f563e26d0.png)

**Comment by Semigradsky** [comment]
From README:
>**Note:** this project uses Electron 32bit version

Just install 32bit Electron locally:
```
npm install --arch=ia32 electron-prebuilt
```

**Comment by ramstein74** [comment]
I did like in the readme.
but when i did
npm install before doing npm install --arch=ia32 electron-prebuilt

i noticed it downloaded a 64bit version of electron


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sem
vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-04-06 11:31 GMT+01:00 Dmitry Semigradsky <notifications@github.com>:

**Comment by Semigradsky** [comment]
Yes. So you have to install it manually.
@appetizermonster, maybe add `postinstall` section to package.json?

**Comment by appetizermonster** [comment]
@Semigradsky Sorry, i don't understand your intention. what can i do for `postinstall`?

**Comment by Semigradsky** [comment]
`npm install --arch=ia32 electron-prebuilt`

**Comment by cpriest** [comment]
I have not run into this issue since v0.52 when I got involved, I know it works in 64 bit as well now.
