### ISSUE TITLE
Bug: could not execute VirtualBox

### ISSUE THREAD

**Issue by SDRLurker** [appetizermonster/hain#105]
**My System Spec**
OS : Windows 8.1 EnterPrise K (64bit)
RAM : 4GB
Hain version : v0.0.4

**Symptom**
1. To search for "VirtualBox" is good.
![image](https://cloud.githubusercontent.com/assets/6982251/14339632/1b6bc1fe-fcbb-11e5-94a1-67599d251f04.png)
2. After 'enter' key, Hain could not execute the "VirtualBox" program.
3. If needed, I will append more information about this issue.

**Comment by appetizermonster** [comment]
Maybe it's broken link. Could you check it?

**Comment by mistic100** [comment]
I also have a few program not launched via Hain :
- Oracle VM VirtualBox
- XnConvert
- Rainmeter
- SketchUp
- ...

**All x64 apps.**
All shortcuts are valid

**Comment by batagliao** [comment]
I also couldnt launch Snipping Tool from Windows 10 64

**Comment by SDRLurker** [comment]
[Oracle VM VirtualBox.zip](https://github.com/appetizermonster/hain/files/209422/Oracle.VM.VirtualBox.zip)
Please refer to the VirtualBox lnk file.

I copied it from ProgramData folder to DeskTop(바탕화면) folder in order to zip it.
After copying it, the icon picture was changed.
This seems to be the reason why Hain couldn't execute this program.

**Comment by appetizermonster** [comment]
I found that shortcut which is owned by `SYSTEM` not a user couldn't be launched by Electron `shell.openItem`. I'm finding a way to solve this problem.

**Comment by appetizermonster** [comment]
@SDRLurker I think it's fixed at [v0.1.0](https://github.com/appetizermonster/hain/releases/tag/v0.1.0), Can you try this?

**Comment by SDRLurker** [comment]
@appetizermonster I have tried to execute Virtual Box. It's a success to execute Virtual Box. Thank you. :+1:

**Comment by appetizermonster** [comment]
@SDRLurker Good!, I close this issue
