### ISSUE TITLE
Bug: /hpm update doesn't work after the first time

### ISSUE THREAD

**Issue by jimbolimbo3** [appetizermonster/hain#108]
After the first time I update a /hpm package, if I try to update another package, the list of package update doesn't appear. If I restart Hain, it works.
An example in the gif: I know it was just one package to update, but the result is the same.
![animation](https://cloud.githubusercontent.com/assets/2467359/14424445/63caf45a-ffe1-11e5-93fa-9e9becdca473.gif)

Edit:
After a restart Hain shows correctly this screen:
![screenshot 7](https://cloud.githubusercontent.com/assets/2467359/14424571/2a05490e-ffe2-11e5-9241-ddfd7869079d.png)

**Comment by Braunson** [comment]
After updating, there is a note at the bottom of Hain saying to `Restart Hain to take effect`

**Comment by jimbolimbo3** [comment]
I noticed, but why I can't see any other updates?

**Comment by appetizermonster** [comment]
@jimbolimbo3 Yes this is a bug. and it was fixed at 38795fc7c49487b50157a1d82ac7d031a18436a1
but it isn't released yet. so i close this issue
