### ISSUE TITLE
Hide "Uninstall" entries in executable/link search

### ISSUE THREAD

**Issue by Calinou** [appetizermonster/hain#11]
Searching for "Sauerbraten" may return the "Uninstall" result before the "Sauerbraten" result, which is typically the one the user wants.

(I'm referring to [this game](http://sauerbraten.org).)

**Comment by appetizermonster** [comment]
thanks for the good idea!, i agree with you. i'll try!

**Comment by zacps** [comment]
Wouldn't it be better to just move it to the bottom of search results?

**Comment by appetizermonster** [comment]
this would better with a new version

**Comment by appetizermonster** [comment]
Fixed at 0f2163579da10fd87786613be5055684cdb70cd5
