### ISSUE TITLE
renderPreview not updating

### ISSUE THREAD

**Issue by mistic100** [appetizermonster/hain#112]
Hello,

I am creating a RSS feed reader plugin https://github.com/mistic100/hain-plugin-rss

I would like to use the "renderPreview" function to display the feed item content.
https://github.com/mistic100/hain-plugin-rss/blob/master/index.js#L151-L153

My problem is it renders well the first item but when I navigate with the keyboard or hover a new item with the mouse, the right content does not changes, it sticks to the first one.

version 0.1.0

**Comment by appetizermonster** [comment]
@mistic100 Oh, renderPreview needs different ids for different items for optimizing performance, i think it may be the reason.

**Comment by mistic100** [comment]
Thank you
