### ISSUE TITLE
Preferences error message

### ISSUE THREAD

**Issue by mistic100** [appetizermonster/hain#113]
I set up this regex validation for URL
https://github.com/mistic100/hain-plugin-rss/blob/master/preferences.json#L21

It works well but Hain directly displays the JSON schema error which is kinda ugly when using a pattern :

> Does not match regular expression "\(?(?:(http|https|ftp):\/\/)?(?:((?:[^\\W\\s]|\\.|-|[:]{1})+)@{1})?((?:www.)?(?:[^\\W\\s]|\\.|-)+[\\.][^\\W\\s]{2,4}|localhost(?=\/)|\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})(?::(\\d*))?([\/]?[^\\s\\?]*[\/]{1})*(?:\/?([^\\s\\n\\?\\[\\]\\{\\}\\#]*(?:(?=\\.)){1}|[^\\s\\n\\?\\[\\]\\{\\}\\.\\#]*)?([\\.]{1}[^\\s\\?\\#]*)?)?(?:\\?{1}([^\\s\\n\\#\\[\\]]*))?([\\#][^\\s\\n]*)?\\)?"

Perhaps Hain could expose a way to customize the error message, for example by extending the JSON schema declaration with a "messages" field.

Similar question on other projects using JSON schema :
https://github.com/geraintluff/tv4/issues/115#issuecomment-41093371

**Comment by appetizermonster** [comment]
@mistic100 it looks your suggestion would be good solution for this, I think i can implement it by referencing your suggestion

**Comment by mistic100** [comment]
Perfect :-)
https://github.com/mistic100/hain-plugin-rss/commit/0f60e0ffc59dc35270eba67b4fb39c2a0bc3027b#diff-db61577cf3cd56d46837c09775052b4bR10
