### ISSUE TITLE
Add Modifier Keys

### ISSUE THREAD

**Issue by ishu3101** [appetizermonster/hain#116]
In Alfred, you could add a modifier for eg: `ctrl + enter` to copy text to the clipboard.  How do you do this in Hain?

**Comment by appetizermonster** [comment]
There is no way to find out modifier keys in plugins for now. it can be useful. but I think it's not good UX. I think Button API can cover most use-cases.

**Comment by ishu3101** [comment]
Why do think the modifier keys does not provide good UX? Are there any examples or plugins that are using the Button API?

**Comment by appetizermonster** [comment]
Currently, there is no Button API yet. but you can see [here](https://github.com/appetizermonster/hain/pull/55) as an example.
and we don't have a place to show how to use modifier keys for users, so i think this isn't good UX.

**Comment by cpriest** [comment]
This has been implemented already in the latest development branch, see #189
