### ISSUE TITLE
Open plugin preferences

### ISSUE THREAD

**Issue by mistic100** [appetizermonster/hain#118]
What about an optional parameter to `openPreferences()` to directly open a plugin tab ?

```js
app.openPreferences('hain-plugin-rss');
```

**Comment by appetizermonster** [comment]
@mistic100 That's a good idea!

**Comment by mistic100** [comment]
Great
https://github.com/mistic100/hain-plugin-rss/commit/0f60e0ffc59dc35270eba67b4fb39c2a0bc3027b#diff-168726dbe96b3ce427e7fedce31bb0bcL205
