### ISSUE TITLE
Add Clipboard History & Snippets

### ISSUE THREAD

**Issue by ishu3101** [appetizermonster/hain#119]
Are there any plans for adding Clipboard History & Snippets like in Alfred to Hain?

**Comment by notatestuser** [comment]
For snippets: [hain-plugin-snippet](https://github.com/k-meissonnier/hain-plugin-snippet)
Watch this space for clipboard history!

**Comment by notatestuser** [comment]
[hain-plugin-clipboard](https://github.com/notatestuser/hain-plugin-clipboard)

**Comment by ishu3101** [comment]
Thanks. I will have a look at these. What do you guys think about including them as part of the default Hain installation.

**Comment by appetizermonster** [comment]
I prefer to keep `hain-plugin-clipboard` as external plugin, Hain should keep its size small.
