### ISSUE TITLE
How to store plugin data ?

### ISSUE THREAD

**Issue by mistic100** [appetizermonster/hain#124]
What is the recommended way to store app data  (cache, history, etc) ?

hain-plugin-steam creates a file in it's own JSON file with a partly hardcoded path (I don't really like it)
https://github.com/KennethWussmann/hain-plugin-steam/blob/master/index.js#L18

If there is nothing existing yet I would suggest some kind of "Storage" object in the PluginContext all cleanly managed by Hain.

**Comment by appetizermonster** [comment]
Actually, there is a storage for each plugin that is undocumented yet. you can access it via `pluginContext.localStorage`, which is [node-persist Object](https://github.com/simonlast/node-persist).
so you can use `pluginContext.localStorage.setItem` or `getItem`.

**Comment by mistic100** [comment]
Great, thank you
