### ISSUE TITLE
Create a json configuration for shortcut, etc

### ISSUE THREAD

**Issue by appetizermonster** [appetizermonster/hain#13]

**Comment by appetizermonster** [comment]
Im currently looking for JSON Schema for implementing user configuration

**Comment by ewnd9** [comment]
@appetizermonster maybe just start with something simple like https://github.com/yeoman/configstore?

**Comment by luisrudge** [comment]
this issue is for making alt+space customizable?

**Comment by appetizermonster** [comment]
@luisrudge right

**Comment by appetizermonster** [comment]
now, im working on it at branch `feature/user_preferences`

**Comment by luisrudge** [comment]
awesome!

**Comment by Fannon** [comment]
Really looking forward to this feature! I've thought about having a JavaScript bases application launcher, too. But you have actually done it and it looks very promising so far!

Regarding the JSON Schema for Links, here are some ideas: 
It could be a good thing that every shortcut gets its own JSON/YAML file, where you can define the actual command to run, one or more keywords and maybe a custom priority, tags and a comment (that may be seached, too). It'd be great to have support for basic arguments.

If you want some second oppinion or an suggestion, I could write a JSON Schema as some suggestion or starting point.

Something that's more advanced but could be a nice alternative to a full fledged plugin, would be .js files, which get some parameters and can (sync or async) execute the code and optionally return some text.

Just some ideas ;)

Best,
Simon
