### ISSUE TITLE
hint don't fully hides

### ISSUE THREAD

**Issue by Andrey-Zhiryakov** [appetizermonster/hain#145]
if i set long string to toast.enqueue, then hint looks like this:
![image](https://cloud.githubusercontent.com/assets/16887205/15357416/5799bdfe-1d07-11e6-803e-d5d18ef1c794.png)

**Comment by appetizermonster** [comment]
Thanks for the reporting, I'll have a look at it.

**Comment by appetizermonster** [comment]
Resolved at 75ba13aff3b73e844533134a5d175f421a7d00e4

**Comment by cpriest** [comment]
I'm going to close this issue as resolved, if it is not, please re-open.
