### ISSUE TITLE
Scroll up and down with Ctrl+J and Ctrl+K

### ISSUE THREAD

**Issue by jminjie** [appetizermonster/hain#146]

**Comment by blainesch** [comment]
It would be more consistent to be cmd+n / cmd+p which is how most terminals and chrome go up and down.

It would be added around [here](https://github.com/appetizermonster/hain/blob/96bc604d8a03b18743ae54e667ae4fa71b040053/app/renderer-jsx/app.jsx#L259)

**Comment by okcompute** [comment]
Could it be configurable? I use `Ctrl+J` and `Ctrl+K` all the time in Vim. This would feel natural for some users like me :smiley:.
