### ISSUE TITLE
What's your proposed plugin API?

### ISSUE THREAD

**Issue by happlebao** [appetizermonster/hain#15]
Hi,
I'm currently the author of [Wox](https://github.com/Wox-launcher/Wox/).
It will suppose js plugin in the future,
so a unified API would benefit user for both application.

**Comment by appetizermonster** [comment]
@happlebao Hello! I'm very big fan of `Wox`, thank you for proposal. sorry, i'm not concerning about unified API for now.
because i think it will be very hard to find a API which fits both needs.

**Comment by happlebao** [comment]
please notify me when plugin API structure of hain is decided.

**Comment by appetizermonster** [comment]
@happlebao okay, i will notify you when its API got stable
