### ISSUE TITLE
support private plugins

### ISSUE THREAD

**Issue by talarari** [appetizermonster/hain#151]
would be cool if hain could support private plugins.
hain is great as a quick interface to inner tools we have at the company, that we might not want to create a public plugin for (and also no one else would use them since they're very specific).

one way that could work is to give hain package manager a concept of repositories and to configure them in settings.

i can think of 3 ways to host a private plugin:
1. network folder
2. private npm modules (some how configure authentication to npm in settings)
3. private npm server (sinopia or other)

thoughts?

**Comment by ewnd9** [comment]
You could also clone plugin sources from private git repository to the [DEV_PLUGIN_REPO](https://github.com/appetizermonster/hain/blob/5068274b919bbb1632cf39a0d717145c1e9897ce/docs/plugin-directories.md) directory and do `npm install` inside to fetch dependencies / transpile sources

**Comment by talarari** [comment]
Yeah , but then i won't be able to install or update then from hpm.
Was thinking of treating private plugins like normal plugins

**Comment by appetizermonster** [comment]
I think it can be achieved by providing custom npm repository url in the preferences.

**Comment by talarari** [comment]
thanks, i'll give it a try when i get to a private plugin. 
closing.
