### ISSUE TITLE
Explorer windows always open with sidepane

### ISSUE THREAD

**Issue by otsaw** [appetizermonster/hain#156]
I have set Explorer i.e. the Windows file browser to not show the filetree sidepane on the left, which is toggleable from Organize / Layout / Navigation pane.

When using Hain to open a directory that sidepane always appears in the Window. Maybe you (or Electron?) are using some weird switches to launch Explorer?

**Comment by appetizermonster** [comment]
No, Hain just uses `electron` API to open explorer.

**Comment by otsaw** [comment]
Yes...

If the problem is in Electron, could you please file a bug there and add a link here. I don't know Electron, what you're using from there or how, so it's a difficult conversation for me to have with them.

**Comment by notatestuser** [comment]
Hain uses a slightly older version of electron - they've released v1.0 now. I scanned over the changelog and saw nothing so here's your issue: electron/electron#6098 :smiley:

**Comment by appetizermonster** [comment]
@notatestuser Thanks!

**Comment by cpriest** [comment]
We're on a much more recent version of Electron now, please re-open if this is still an issue.
