### ISSUE TITLE
Highlight a title when typing

### ISSUE THREAD

**Issue by likerRr** [appetizermonster/hain#159]
@appetizermonster Hi,

I noticed when I type embed hain command like `/hpm install` it's matched part becomes bold. But when I type command in my custom plugin it doesn't.

Could you please explain, how to achieve such behavior?

<p align="center">
  <img src="http://g.recordit.co/YlrTcMjrEG.gif" width="600"/>
</p>

**Comment by notatestuser** [comment]
One way is to use the fuzzy matching util with something like this:
```js
const matchutil = context.matchutil;
const matches = matchutil.fuzzy(results, query, x => x);  // assuming `results` is a set of strings
matches.forEach((match) => {
    const title = matchutil.makeStringBoldHtml(match.elem, match.matches);
    res.add({
        title: title,  // this now contains your <b>'s
        // ... 
    })
});
```

**Comment by likerRr** [comment]
@notatestuser sounds interesting, will try, thx

**Comment by toXel** [comment]
@likerRr if you still need it: [this](https://github.com/appetizermonster/hain/blob/master/app/main/plugins/hain-package-manager/index.js#L118-L125) is the part in the Hain source code.

**Comment by likerRr** [comment]
@toXel great, thx!
