### ISSUE TITLE
Add copy function when calucate

### ISSUE THREAD

**Issue by Galliver7** [appetizermonster/hain#163]
When calclation(hain-plugin-math) done, copy answer automaticaly. 
This feature will be more useful Hain.
![2016-06-26_02h22_53](https://cloud.githubusercontent.com/assets/8030470/16358110/e4ae02d0-3b44-11e6-9a4e-ade5afe98fa6.png)

**Comment by appetizermonster** [comment]
I suppose it can be supported by options. add this into backlog.

**Comment by appetizermonster** [comment]
Resolved at 1dec88178c4a0c939cd21045d3584a9429d702bf
