### ISSUE TITLE
Plugin Method "PluginActive"

### ISSUE THREAD

**Issue by FreaKzero** [appetizermonster/hain#166]
An abstraction like "PluginActive()" if the plugin command is used would be quite useful - ran into this problem with my cmdow plugin - and cant solve my Problem elegantly.

This abstration should be initiated once when someone types /plugin in the Searchbar - something like "componentDidMount()" in React.

**Comment by appetizermonster** [comment]
There is a `startup` method. I suppose this can be satisfied with `startup`.
or you can make it your own abstraction using boolean flag in `search` method.
e.g.
```javascript
let activated = false;

function search(query, res) {
  if (!activated) {
    onActivate();
    activated = true;
  }
  onSearch(query, res);
}

function onActivate() { ... }
function onSearch(query, res) { ... }
```

I think that we should avoid adding another `activate` event to keep api complexity as low as possible.

**Comment by FreaKzero** [comment]
Isnt the startup() only executed when hain is started or did i understand this the wrong way ?

Im just asking about this - so i dont have to debounce ajax requests or command line stdouts in the search() Method.
