### ISSUE TITLE
Allow to send payload from search to execute

### ISSUE THREAD

**Issue by schmic** [appetizermonster/hain#167]
I started to write the hain-plugin-alias, an alias plugin for hain. 

Basic idea is to define alias-names that start commands, like "ssh" starts "putty.exe -ssh". Now I need to be able to send commandline parameters from the search to the execution.

What I would like to do is search: "ssh my.hostname.tld"
Which runs "putty.exe -ssh my.hostname.tld".

Any ideas how to achive that?

Plugin-URL: https://github.com/schmic/hain-plugin-alias

**Comment by appetizermonster** [comment]
You can pass whole query to execute function by assigning whole query as payload in `search` function.
and you can use **Regular Expression** to parse query. 
or you just find the first whitespace character and split text into two parts using the whitespace, then the first part will be command and the rest will be parameters.

**Comment by schmic** [comment]
@appetizermonster I already did excactly like you said. Cheers.
