### ISSUE TITLE
Hain plugins are not loading if certain node modules are required?

### ISSUE THREAD

**Issue by ngergo6** [appetizermonster/hain#168]
I was developing a plugin that emulates key presses using [RobotJS](https://github.com/octalmage/robotjs). When I reloaded Hain for the first time after I thought I was finished, the plugin did not load.

I tried a lot of things until I decided to comment out the parts where I require and use RobotJS and the plugin loaded successfully (although it obviously did nothing).

Are there certain node modules that Hain does not support in plugins or might this be some kind of compatibility issue?

Thanks in advance!

**Comment by schmic** [comment]
@ngergo6 and the modules where available in the plugins directory where the plugin is installed?

**Comment by ngergo6** [comment]
@schmic yes it was installed using npm and also added as a dependency to the package.json file.

**Comment by ngergo6** [comment]
I just found out that the problem is not with Hain but with Electron.

Seems like Electron can't handle some node modules. I think it has something to do with it having a different context than native nodejs applications.

I will close this issue now, but it's still an information that is good to know.

**Comment by appetizermonster** [comment]
Currently, Hain can't handle native module (made by C++), maybe it can be the problem.

**Comment by ngergo6** [comment]
Thank you for clarifying this :)
