### ISSUE TITLE
High CPU consumption

### ISSUE THREAD

**Issue by StefanFl** [appetizermonster/hain#171]
Hain is a great tool, thank you very much. Unfortunately I cannot run it on my laptop all the time because it often consumes a lot of CPU power, see screenshot.
![2016-07-27 14_58_24-ressourcenmonitor](https://cloud.githubusercontent.com/assets/2698502/17176036/13e259be-540b-11e6-92eb-b50f84cd9128.png)
Every few seconds it uses ca. 15 % CPU for quite a while and forces the CPU to run on full speed. This decreases the life span on battery considerably.

**Comment by appetizermonster** [comment]
This seems to be very serious problem. I believe some plugins can cause this kind of problem. 
Can you show me your installed plugin list?

**Comment by StefanFl** [comment]
It is the hain-package-manager and the hain-plugin-filesearch, nothing more.

**Comment by appetizermonster** [comment]
then, I suppose `hain-plugin-filesearch` can cause this problem when another program touch files on the disk very actively.
I'll try to fix it. and please send me a log file if possible (you can find it at `%AppData%\Local\hain\app-0.4.1\hain-debug.log`).

**Comment by StefanFl** [comment]
Good idea to have a look at the log. Found the cause. I have a suite of portable apps installed and configured to be searched by Hain. But in this directory with all its subdirectories there are are lot of file changes. I think that's the reason, why Hain reindexes this directory very often.

This issue is solved and I close it. But that leads me to a feature request, I will describe that in another issue.
