### ISSUE TITLE
Feature request: Performance improvements for directories where files often get changed

### ISSUE THREAD

**Issue by StefanFl** [appetizermonster/hain#172]
The file search plugin currently indexes complete directories. This leads to performance problems when files often get changed in such a directory, e.g. when it contains portable apps, where programs and data are mixed. Two ideas to improve that situation:
1. It could be possible to specify a list of file extensions to be indexed in that directory, e.g. exe, bat, lnk. The indexer should run only when a file with an extension in that list got changed or added or removed.
2. You could specify directories that are not indexed automatically but only manually.
3. Another solution

**Comment by cpriest** [comment]
There have been significant improvements in this on v 0.6, please give that a try and re-open if this is still an issue.
