### ISSUE TITLE
recent items stays at top 

### ISSUE THREAD

**Issue by PiratedVirus** [appetizermonster/hain#174]

**Comment by appetizermonster** [comment]
I couldn't understand of the issue. Can you explain it more?

**Comment by acbee** [comment]
Recent Items is obviously a feature, not an issue, but it's not one that I enjoy either. I'd prefer to be able to turn it off or for it only to show up if what I'm typing is somehow related to one of the recent items. If I've previously opened Excel, and I start typing something that contains some of the same letters that are in Excel's PATH, I don't think Excel should be matched.

**Comment by cpriest** [comment]
Give the latest v0.6 a try and see if this still an issue.  If so, please re-open.
