### ISSUE TITLE
Add tab(expand) indicator

### ISSUE THREAD

**Issue by rickmed** [appetizermonster/hain#176]

**Comment by appetizermonster** [comment]
Tab only works on some plugins. others might not work.

**Comment by rickmed** [comment]
thanks for the response @appetizermonster ! Shouldn't it be a core feature?

**Comment by appetizermonster** [comment]
I have a plan to add indicator that shows whether tab has functionality or not.

like chrome:
![image](https://cloud.githubusercontent.com/assets/6244462/17665582/db985b9a-6336-11e6-97bc-c7775397090a.png)

**Comment by rickmed** [comment]
@appetizermonster oh I misunderstood. I assume now not all plugins (due to their nature) use this core feature...

**Comment by appetizermonster** [comment]
yes, right.

**Comment by appetizermonster** [comment]
Resolved at f04d61ec15443a7defde35cff9d7eb53420f04a4
