### ISSUE TITLE
Error when running Hain in develop branch

### ISSUE THREAD

**Issue by gsgeschke** [appetizermonster/hain#183]
I am unable to run Hain in the develop branch with the following error:

![image](https://cloud.githubusercontent.com/assets/2947244/18133910/3f2df7fc-6f51-11e6-846f-b8d2f9c8bdc3.png)

When I take the branch back to 5611831d2f4ad462857fd24d14077c456b9a1be9, then it starts up without error. The error seems to have been introduced in the 98660dc99c22113fd19dabbb38e6056587e6e7c4 merge.

Any suggestions?

**Comment by appetizermonster** [comment]
please pull `develop` branch again. i pushed much of changes.

**Comment by gsgeschke** [comment]
You're right, the `develop` branch starts up fine now.
