### ISSUE TITLE
Preferences Input not working

### ISSUE THREAD

**Issue by appetizermonster** [appetizermonster/hain#184]
Version: Hain 0.5.0

**Comment by gsgeschke** [comment]
@appetizermonster I think the problem occurs here:

https://github.com/appetizermonster/hain/blob/master/app/renderer-jsx/schema-form/schema-form.jsx#L41

The _path_ has a leading dot and that causes _lo_set_ to create a new object in the model for the preference change.

For example, after loading preferences, and clicking the 'Clear query after window is closed" checkbox, the preferences that gets written looks like this:

`{"":{"clearQuery":true},"clearQuery":false,"customQueryShortcuts":[],"proxy":{"host":"","port":80,"useProxy":null},"shortcut":"alt+space"}`

Notice that there are now two _clearQuery_ elements, the first one on the empty "" object.

**Comment by appetizermonster** [comment]
Resolved at 55345eb72cbc9ccac1b64efb052df241b0057817
