### ISSUE TITLE
Feature request: Alternative execution

### ISSUE THREAD

**Issue by krokofant** [appetizermonster/hain#189]
It would be nice to be able to detect if the ALT key is pressed upon execution. Then plugin developers could implement alternative actions for a single subject.

A simple example is wheter a URL should be opened in the browser or copied to the clipboard.

Any ideas on how and where this should be implemented?

**Comment by appetizermonster** [comment]
Yes It must be useful feature. I believe some implementation like chrome's quick-search can be used for this feature.

**Comment by cpriest** [comment]
This could be added pretty easily I think and passed in via the execute() function, I'll take this one on.

**Comment by cpriest** [comment]
This should be taken care of.  See the pull request for short-term documentation.

**Comment by krokofant** [comment]
Nice! I'll try it out the next time I boot Windows!

**Comment by cpriest** [comment]
Note you'll need to checkout the development branch and all that's 
required there to try out the feature.

You may also be interested in a typescript definition file I have built 
for hain, right now its located here:

https://github.com/cpriest/hain-plugin-psl/blob/master/%40types/hain-plugin.d.ts

-Clint
