### ISSUE TITLE
Distribute via chocolatey

### ISSUE THREAD

**Issue by FlorianRappl** [appetizermonster/hain#20]
First of all: great job :+1:!

I think this useful tool should definitely be distributed as a binary, e.g., via [Chocolatey](https://chocolatey.org), as well. That would make it very easy to be obtained and integrated in system installation / provisioning routines.

If you need or want assistance or help I would love to contribute.

**Comment by appetizermonster** [comment]
Thanks for your interest!, it will be nice if **Hain** can be distributed via **Chocolatey**.
I will be very appreciated if you can contribute for it.
actually, i dont know nothing about **Chocolatey**
