### ISSUE TITLE
Add the fact that the author field is mandatory in the documentation

### ISSUE THREAD

**Issue by natinusala** [appetizermonster/hain#204]
Hello,

I've made a small plugin to open anything in a browser using Google's Feeling Lucky. It works fine in development mode so I thought that I could publish it (hain-plugin-go on npm).

However, after publishing it, Hain does not seem to want to install it using /hpm install :

    2016-12-03T01:19:43.826Z - debug: Installing hain-plugin-go
    2016-12-03T01:19:45.593Z - debug: hain-plugin-go TypeError: Cannot read property 'name' of undefined

I unfortunately don't have more details on the error, but I do know that it happens in the `installPackage` function of the hpm plugin code (index.js:251).

As you can see on the code here : https://github.com/natinusala/hain-plugin-go the plugin is well-formed, and actually works well in dev mode. What is causing this issue ?

Thanks !

**Comment by natinusala** [comment]
Turns out that the `author` field is required, otherwise it causes this error. It should be added to the documentation.

**Comment by appetizermonster** [comment]
@natinusala Thanks for the investigation! 😄  I'll add it to the documentation.

**Comment by appetizermonster** [comment]
Resolved at 9eb8eca2b811fc22300c0af675b0789be3abc55f, Thanks!
