### ISSUE TITLE
Add dependencies to package.json

### ISSUE THREAD

**Issue by tylerjvick** [appetizermonster/hain#211]
It seems that Electron has issues running when modules aren't defined in the dependencies section of package.json (not devDependencies). I'm not sure when this started, but having to manually install each package when receiving an error is quite tedious.

Has anyone else encountered similar issues?

**Comment by cpriest** [comment]
I think the only one is webpack, I've seen that before but nothing else.

**Comment by cpriest** [comment]
I believe this is due to a downstream dependency requiring an invalid version number, I just manually install the one item and am done with it.  If you happen to track down what it is, perhaps you can contact that packages maintainer to have them address the issue.
