### ISSUE TITLE
[v0.6] /hain command does not return anything

### ISSUE THREAD

**Issue by KroniK907** [appetizermonster/hain#218]
When I first open up Hain it lists the /hain command as a way to see a list of commands, but it returns no results. 

See screenshot:
http://puu.sh/tVOKo/b9be04c49f.png

**Comment by appetizermonster** [comment]
Thanks for reporting issue.
This issue will be fixed very soon.
Thank you

**Comment by appetizermonster** [comment]
this issue has been resolved with v0.6.x
now, `/hain` command shows available commands.
