### ISSUE TITLE
No icon when I search for something

### ISSUE THREAD

**Issue by maximemhd** [appetizermonster/hain#225]
Hello,
Is it normal that I have no icon of applications that I search? In place of the icon, I have this:
![image](https://cloud.githubusercontent.com/assets/9150109/23623774/8ca63eb4-02a3-11e7-928f-ce978c534bf8.png)
(like an error for the icon)

Thank you!
Maxime

**Comment by natinusala** [comment]
I have the same issue. It appeared after making the latest update (updating from 0.6 to 0.6.1).

**Comment by ingro** [comment]
Yep, same here on Windows 10.

**Comment by appetizermonster** [comment]
i'm fixing this issue now

**Comment by appetizermonster** [comment]
This issue has been resolved with [v0.6.2](https://github.com/appetizermonster/hain/releases/tag/v0.6.2)
Please try it.

**Comment by maximemhd** [comment]
Thank you, it works !
