### ISSUE TITLE
Testing Plugins 

### ISSUE THREAD

**Issue by Braunson** [appetizermonster/hain#26]
The docs don't have any info on locally testing (`Run your plugins`) a plugin other than putting it in the `appdata/hain-user/devplugins` folder to which nothing happens when you do so, I've tried restarting hain, looking for my dev plugin in the list, in the 'install list' and still my plugins do not display anywhere.. how can I test this before publishing it?

**Comment by leonardosnt** [comment]
Look hain.log...

`C:\Users\...\AppData\Local\hain\app-0.0.2\hain.log`

Can be a syntax error.

**Comment by Braunson** [comment]
@leonardosnt Thank you sir, I see it's not able to find a module.
