### ISSUE TITLE
How to index custom folders / files?

### ISSUE THREAD

**Issue by farzher** [appetizermonster/hain#27]
I want to run this: `Z:/dropbox/my_project/run.bat`

In Launchy I told it to index the dropbox folder, then I was good to go. What can I do here?

**Comment by appetizermonster** [comment]
Currently, there is no support for custom folders (or files) to index,
i will be working on it.

**Comment by appetizermonster** [comment]
#13

**Comment by appetizermonster** [comment]
Fixed at e5385c07196b11825f2e9e24a19a774161c6fdbb
