### ISSUE TITLE
/hpm install - show and sort by count of downloads

### ISSUE THREAD

**Issue by Semigradsky** [appetizermonster/hain#30]
It would be great to see the most popular plugins at once.

**Comment by appetizermonster** [comment]
Good idea!, im looking for the way for implementing it, have any idea?

**Comment by Semigradsky** [comment]
For getting count of downloads: https://api.npmjs.org/downloads/point/last-week/hain-plugin-github

**Comment by appetizermonster** [comment]
good! thanks! i should be working on it

**Comment by appetizermonster** [comment]
Its implemented with [v0.2.0](https://github.com/appetizermonster/hain/releases/tag/v0.2.0)
