### ISSUE TITLE
Problem with opening dev tools

### ISSUE THREAD

**Issue by Semigradsky** [appetizermonster/hain#31]
In [docs](https://github.com/appetizermonster/hain/blob/master/docs/plugin-context-logger.md):
>**Note:** You can see logging messages in `Chrome Developer Tools` in the app.
You can open `Chrome Developer Tools` by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> in the app.

I tried <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>, <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>, <kbd>F12</kbd>...
There are no results.

I am using v0.0.2-rc4 (HainSetup-ia32.exe)

**Comment by appetizermonster** [comment]
Fixed at afaaeedc82bb5de7a24ac31ab418b27eb7a163ae
