### ISSUE TITLE
Don't delete query when reopen hain

### ISSUE THREAD

**Issue by roose** [appetizermonster/hain#35]
Don't clear last query, just select it

**Comment by appetizermonster** [comment]
I couldn't agree with this in my usecases, but i think it can be added as an option

**Comment by roose** [comment]
@appetizermonster thank you )

**Comment by farzher** [comment]
+1 I'm almost always using this just to run whatever app I'm currently working on. It's super annoying that I have to keep typing the app name to run it.

I'll add to the feature suggestion that there should be a history of recent commands that I can scroll through. Probably the up arrow should go through recent commands (kind of like how shells work)

**Comment by appetizermonster** [comment]
Resolved at 3958a0f7b799dcc418be554dfac0b2a063c5a2fa
