### ISSUE TITLE
TypeError: Error Processing argument at index 0, conversion failure from

### ISSUE THREAD

**Issue by joaovcarvalho** [appetizermonster/hain#38]
![screenshot 2016-03-25 14 33 13](https://cloud.githubusercontent.com/assets/2847790/14046056/a460b642-f296-11e5-8d39-f2260aa114e3.png)

I get this error and trying to execute from the windows menu after pressing the windows key.

**Comment by appetizermonster** [comment]
Could you try the new version?
https://github.com/appetizermonster/hain/releases/tag/v0.0.3

**Comment by joaovcarvalho** [comment]
The new version is working just fine. Thanks !

**Comment by appetizermonster** [comment]
okay fine!
