### ISSUE TITLE
Proxy?

### ISSUE THREAD

**Issue by avindra** [appetizermonster/hain#4]
Is there a way yet to get it to work behind a proxy?

hpm is just spinning currently

**Comment by appetizermonster** [comment]
sorry, there is no proxy support yet.
for now, i dont have an idea how to implement it.

**Comment by toXel** [comment]
Shouldn't it use the .npmrc file from the user folder?
There you can set a proxy and http-proxy variable.

**Comment by appetizermonster** [comment]
@toXel it may not work with .npmrc, hain doesn't use **npm**. but it uses internal package installing implementation which don't care proxies yet.

**Comment by toXel** [comment]
@appetizermonster Ok I see... so we have to wait until it is supported.

**Comment by debovema** [comment]
+1

**Comment by TuckerWhitehouse** [comment]
What about the `proxy`, `http_proxy`, or `https_proxy` environment variables?

**Comment by Muffinoota** [comment]
+1 my team would love to use it, but we have a proxy at work that has issues with anything https going through

**Comment by appetizermonster** [comment]
Im working on it

**Comment by appetizermonster** [comment]
Resolved at 3192c3b6f095b51d22c17e68b57f16c7a913e087
You can open preferences by entering `/preferences` and you can set proxy settings
