### ISSUE TITLE
Could you add more run-like features?

### ISSUE THREAD

**Issue by Gum-Joe** [appetizermonster/hain#42]
I just checkout out hain and it is brilliant, however, I think you could add a lot more standard features
**NB:** I know most of these could be added as plugins, but it seems more convenient to ship them out of the box.

Features:
1. Environment variables - in run, you can type `%appdata%` and it would launch/run what the environment variable `%appdata%` is equal to (in this case, open `C:\Users\<user>\AppData\Roaming`)
2. Ship a plugin that allows you to run `/opendir <dir>` to open a dir (another run feature - could be a plugin)
3. Most used/favourite apps - this would be quite good as it would let you quickly run your most used/favourite apps, rather than type them in each time
4. Add an `/update` command to apply hain updates.
5. Repo: Add a `CONTRIBUTING.md` so issues that you don't want don't happen (hopefully) and to give instructions about contributing

Hope you continue developing!
Thanks in advance.

**Comment by appetizermonster** [comment]
I couldn't agree with no 1, 2. i think it would be better to make plugins support it.
4: It's very reasonable. it should be added.
5: I'll merge your pull request #49 
Anyway, Thank you for your advice! :+1:

**Comment by Gum-Joe** [comment]
Your welcome. Do you know where the documentation for making plugins is? Does the api support opening file explorer (for 1 and 2)?
Also, is 3 already supported automatically (I know there is an updater shipped with Hain)

**Comment by Gum-Joe** [comment]
@appetizermonster I'll keep this issue open until the features that you are going to add are added/made into plugins

**Comment by Gum-Joe** [comment]
#49 merged. I'm going to assume 3 and 4 will be added at a later date. Closing for now.
@appetizermonster: Feel free to reopen this issue at a later date.
