### ISSUE TITLE
Executable search only looks on the system drive.

### ISSUE THREAD

**Issue by harderthanfire** [appetizermonster/hain#5]
I like a lot of people install some software off my small ssd and instead on a large hdd. Hain seems to only find files on the system drive and in certain directories making it almost useless. Allowing the user to change these paths without needing to rebuild would be great.

**Comment by appetizermonster** [comment]
okay, currently, there is no support for configuring additional directories.
there is no way to configure user settings for now.
it will be implemented soon. please keep watching it.

**Comment by appetizermonster** [comment]
#13
