### ISSUE TITLE
Press alt+space again to close it

### ISSUE THREAD

**Issue by taylankasap** [appetizermonster/hain#52]
I think OS X spotlight was like that.

**Comment by akkatracker** [comment]
+1 
I was using Launchy before on windows and it has this. Very useful for fast navigation. In fact until hain supports this I think I'll go back to Launchy.

**Comment by akkatracker** [comment]
Any reason this was closed? Can't see a commit that fixes it...

**Comment by taylankasap** [comment]
Sorry, I took it for granted when he said "It fixes #52". Doesn't it work?

**Comment by akkatracker** [comment]
Ah didn't see that. Feel free to close. I'll test when I'm home.

Thanks!
