### ISSUE TITLE
Allow a plugin to use its own shortcut

### ISSUE THREAD

**Issue by notatestuser** [appetizermonster/hain#57]
It would be nice to allow plugins to define their own keyboard shortcuts for direct access like in Alfred. A perfect implementation would consider repeat or double-tap key presses as shortcuts (e.g. alt + alt)!

**Comment by appetizermonster** [comment]
I think this can be implemented via preferences

**Comment by appetizermonster** [comment]
Resolved at 87c0dc048484e569a95748a90a6660a529743533
