### ISSUE TITLE
Add functionality to open folders in file explorer?

### ISSUE THREAD

**Issue by sethxd** [appetizermonster/hain#6]
This is awesome, and I like it a lot better than the launcher I've been using. The only feature missing I use a lot is to search for & open folders. Any chance you're planning to add this functionality?

**Comment by appetizermonster** [comment]
@sethxd yes, i have a plan for implementing it, im finding a proper algorithm to score both folders & files.

**Comment by sethxd** [comment]
great to hear, thanks!

**Comment by appetizermonster** [comment]
Implemented at 0f2163579da10fd87786613be5055684cdb70cd5
