### ISSUE TITLE
Pressing tab should auto-complete

### ISSUE THREAD

**Issue by notatestuser** [appetizermonster/hain#61]
Pressing tab in this situation should trigger an auto-complete, jus' like our beloved Alfred:

<img width="600" alt="hainac" src="https://cloud.githubusercontent.com/assets/1255926/14082422/62fc683c-f542-11e5-96ff-e75c73230010.png">

**Comment by appetizermonster** [comment]
Good point!
Pressing `enter` acts like it for now.
but I agree pressing `tab` would be also nice

**Comment by appetizermonster** [comment]
Resolved at 4ac714b757c97d275f4f66fd961ee4aa410f40e9

**Comment by notatestuser** [comment]
Awesome, thank you!
