### ISSUE TITLE
Demo gif key presses

### ISSUE THREAD

**Issue by ktmn** [appetizermonster/hain#66]
Sorry that isn't really relevant to this repo, but is there any particular software at work to visually show the key presses in the demo gif? 

https://raw.githubusercontent.com/appetizermonster/hain/master/docs/demo.gif

**Comment by ishu3101** [comment]
Check out [KeyCastOW](https://brookhong.github.io/2014/04/28/keycast-on-windows.html). It is a keystroke visualizer for Windows that lets you easily display your keystrokes while recording screencasts.

**Comment by ktmn** [comment]
Awesome, thanks!
