### ISSUE TITLE
Please add Plugin "amzn" to plugin-docs.md

### ISSUE THREAD

**Issue by TheBuzzDee** [appetizermonster/hain#69]
Could you please add my Amazon-Plugin (hain-plugin-amzn) to your plugin-docs.md ?
https://github.com/TheBuzzDee/hain-plugin-amzn/

Made another hain-plugin for my imagehosting site:
https://github.com/TheBuzzDee/hain-plugin-buzzpics

**Comment by Braunson** [comment]
@TheBuzzDee Add it in your self by create a PR for it to the `develop` branch :)

**Comment by Braunson** [comment]
@TheBuzzDee I just added it in for ya, just waiting for the PR to be approved and merged :+1:
