### ISSUE TITLE
How to debug Plugins?

### ISSUE THREAD

**Issue by ishu3101** [appetizermonster/hain#77]
How do you debug plugins when you are developing plugins?

**Comment by Semigradsky** [comment]
I just insert `console.log` :smile:

**Comment by ishu3101** [comment]
But then where do you see the console log?

**Comment by notatestuser** [comment]
Press F12 - it'll open devtools.

**Comment by ishu3101** [comment]
Pressing F12 does nothing.

**Comment by notatestuser** [comment]
Do you have afaaeedc82bb5de7a24ac31ab418b27eb7a163ae?

**Comment by ishu3101** [comment]
No was using v0.0.2-rc4, Updated to the latest release which is v0.0.3.

**Comment by KennethWussmann** [comment]
Better use `PluginContext.Logger.log("message");` as mentioned [here](https://github.com/appetizermonster/hain/blob/master/docs/plugin-docs.md#very-important-notice).

**Comment by ishu3101** [comment]
I have noticed that using `console.log` causes the plugin to break in v0.0.3 but in v0.0.2-rc4 it did not cause any problems

**Comment by sethxd** [comment]
I was having this same issue trying to use console.log. Fixed it by including this line just inside module.exports: `const logger = pluginContext.logger`

And calling it like this: `logger.log("Hello world!")`

**Comment by likerRr** [comment]
Hey everyone. 

Sometimes I face an issue when DevTools shows just `Object{}` without any properties (except native prototype) for my objects or even `null` at all (but properties exist and they're accessible). Can't provide an example for the first case, because it doesn't work on simple code, but here is a simple version of second case (`lodash` should be installed):

```javascript
let _ = require('lodash');

module.exports = (context) => {
  "use strict";

  function startup() {
    context.logger.log(_); // -> null
    context.logger.log(_.identity(2)); // -> 2
  }

  return {startup};
};
```

What's the matter?

**Comment by likerRr** [comment]
@appetizermonster have ideas?

**Comment by appetizermonster** [comment]
There is no advanced way to debug plugins for now. we should make it.
not in docs, but you can use `console.log` in the plugin if you launch hain on commandline prompt. (but you should remove them in the production)
so it may be helpful for debugging.

**Comment by cpriest** [comment]
I have v0.5.2 which should include afaaeed but F12 does not do anything, F5 does however work which I see that commit also had some code in for.  Is F12 expected to be working right now?

**Comment by appetizermonster** [comment]
@cpriest I'll take a look at it, thanks for the reporting

**Comment by abinadi** [comment]
I had the same issue as @cpriest. I'm on v0.5.2 and F12 does nothing. Not sure if it is pertinent, but I used the pre-built binary.

**Comment by TheElf** [comment]
F12 should be fixed now. F12's handler was firing, but the dev tools weren't being opened properly

see #212
