### ISSUE TITLE
Does the hain-package-manager auto-update installed plugins?

### ISSUE THREAD

**Issue by KennethWussmann** [appetizermonster/hain#78]
Hey,

first of all, hain is amazing, thanks for making this :smile: 
Does the `hain-package-manager` automaticlly update my installed plugins?
If not I'll implement it to my plugins by myself.

thanks,
~ Kenneth

**Comment by appetizermonster** [comment]
@KennethWussmann it doesn't auto-update installed plugins, but v0.0.4 support update-by-user functionality

**Comment by KennethWussmann** [comment]
Okay, thank you :smile:
