### ISSUE TITLE
Crash with Alt + Space

### ISSUE THREAD

**Issue by fartbagxp** [appetizermonster/hain#8]
On Windows 10 with a 4k resolution monitor.

Alt + Space causes the following error to pop up.
![image](https://cloud.githubusercontent.com/assets/8839850/13975570/2a391dba-f08d-11e5-93cf-ef5c95fde624.png)

It works if I go directly to the executable and run that.

**Comment by appetizermonster** [comment]
@fartbagxp thanks for reporting a bug, i'll inspect it

**Comment by will-hart** [comment]
Same error with Win 10, 3840x2160 resolution, v0.0.2-rc3. 

The error occurs _after_ the first usage if it is then minimised and I hit `alt+space`. I get the same if I double click on the icon in the system tray. The app loads up OK the first time after it is restarted.

**Comment by appetizermonster** [comment]
@fartbagxp @will-hart 
i think i fixed an bug for this issue, but i could'nt test it properly.
following is the download link for the test version, could you test it and report the result?

https://github.com/appetizermonster/hain/releases/download/untagged-f981d3beb39f4ca7113a/HainSetup-ia32.exe
or
https://github.com/appetizermonster/hain/releases/download/untagged-3a8b99667253c69a1f07/Hain-win32-ia32.zip

**Comment by fartbagxp** [comment]
Downloaded the zip file, unzipped it.

Alt + Space works for me now, no crashes.
Thank you!

**Comment by appetizermonster** [comment]
@fartbagxp Thanks for your testing, i guess a bug has fixed, so i close this issue.
