### ISSUE TITLE
Not working with Gulp 3.9.1

### ISSUE THREAD

**Issue by jieverson** [appetizermonster/hain#83]
I'm having problem running **gulp** command. It seems that it's 'cause of the **const** instead of **var**.
I think i might be losing some package. Anyone had this problem?
![gulp](https://cloud.githubusercontent.com/assets/1031323/14216295/69b4834c-f81e-11e5-8dfb-ab41dbb6125e.PNG)

**Comment by Semigradsky** [comment]
Gulp version?
```
> gulp -v
```

3.9.0 works normal for me

**Comment by jieverson** [comment]
v 3.9.1

But I don't think it stop reading **const** and **() =>** function styles =s

**Comment by Semigradsky** [comment]
Oh, looks like outdated nodejs version. My version 4.2.1

**Comment by jieverson** [comment]
I installed gulp 3.9.0 and everything start working.
