### ISSUE TITLE
Awesome app

### ISSUE THREAD

**Issue by iamtekeste** [appetizermonster/hain#86]
I just wanted to say this is really cool app and also if you have the time it would be great if you could write an article on how you achieved plugin based workflow. I tried to follow your code and the Plugins api but I got lost somewhere
Again great Job!  :+1:

**Comment by appetizermonster** [comment]
@iamtekeste First of all, Thank you for your interest.
and i want to describe the plugin architecture, but its to hard to write an article in english for me.
so Sorry, haha.
if you still have an interest for plugin, ask me on Gitter
anyway thank you!

**Comment by iamtekeste** [comment]
Its cool man! My goal was to create something like that for Ubuntu. I like the plugin based development. Maybe a simple flow chart / diagram that shows how things interact with each other. Just a very high level explanation. And your English is good ! :)

**Comment by appetizermonster** [comment]
@iamtekeste Sorry for late answer, i dont have much time to write an article :disappointed: for now, so it will take some time.

**Comment by akkatracker** [comment]
If you write it in Korean maybe we can find someone else to translate it or we can plug it into Google Translate. 

Thanks for the work by the way!

**Comment by cpriest** [comment]
I'm familiar enough with the hain code base, the simple answer is as such:

[Renderer Thread] <-IPC-> [Main Thread] <-IPC-> [Worker/Plugin Thread]

These three processes communicate via electron IPC channels with JSON serializable message passing.  Some examples of this would be workerClient.js and workerProxy.js.
